---
- hosts: all
  become: yes
  tasks:
  - name: install webserver
    apt:
      name: apache2
      state: present

  - name: start webserver
    service: 
     name: apache2
     start: started  

  - name: install httpd
    yum:
      name: httpd
      state: present

  - name: start httpd
    service: 
     name: httpd
     start: started
  